### ISSUE TITLE
Use POPF 

### ISSUE THREAD

**Issue by RodrigoCodeBernardo** [jan-dolejsi/vscode-pddl#101]
Hello,
I’m using the PDDL extension in vscode, and I want to use the POPF planner, only it keeps giving me this error:

```
zsh: exec format error: /Users/rodrigobernardo/Desktop/PDDL_CODE/popf.exe
rodrigobernardo@MacBook-Pro-de-Rodrigo PDDL_CODE %     
```

The domain and the problem are fine because I already tested with the default planner.
The POPF executable, I took from the ROSPLAN page on GitHub

Could the file extension be wrong? What could I be doing wrong?

**Comment by RodrigoCodeBernardo** [comment]
I tried using it on linux and it works. Where can I get the extension to use on Mac?

**Comment by jan-dolejsi** [comment]
As discussed in the Slack group: there is only one build of the PDDL extension for VS Code. It runs cross platform as it depends on node.js. But the planner executable runs in a process spawned by node.js on your local operating system. On Windows, you need a windows build of the planner. On Mac, you need a MacOS/Darwin build of the planner.
No, the `popf.exe` would not run on Linux.
