### ISSUE TITLE
:DURATIVE-ACTIONS

### ISSUE THREAD

**Issue by wuchun123** [jan-dolejsi/vscode-pddl#102]
/tmp/solver_planning_domains_tmp_4fYsTgG2CMmMp/domain.pddl: syntax error in line 8, ':DURATIVE-ACTIONS':
domain definition expected
☒ 2. Evaluating temporal/numeric plans (1.784 sec)
    No plan found

the problem will appear when I run the 'Airport Single aircraft .....'

**Comment by jan-dolejsi** [comment]
This is expected. The free online hosted planner at solver.planning.domains only solves propositional planning problems. What you need for the airport (and many other problems) is a temporal and numeric. A planner that supports PDDL2.1. See the planners that have the capabilities:

https://planning.wiki/ref/planners/tags/temporal
https://planning.wiki/ref/planners/tags/numeric

There is/was a plan to make the free online solver selectable. You can find out about that by asking in the [slack group mentioned here](https://planning.wiki/).
