### ISSUE TITLE
Please use category "Programming Languages" rather than "Language Packs"

### ISSUE THREAD

**Issue by gregvanl** [jan-dolejsi/vscode-pddl#13]
Category "Language Packs" is for display language extensions (ex. German, Bulgarian). Extensions which contribute general programming language features (syntax highlighting, code completions) should use "Programming Languages"

**Comment by gregvanl** [comment]
Looks like the Marketplace is adding categories "Other" and "Language Packs" automatically. I would recommend adding the sections below to your package.json

```json
"categories": [ "Programming Languages", "Snippets" ],
```

**Comment by jan-dolejsi** [comment]
Thanks. Fixed in 2.6.5.
