### ISSUE TITLE
Failed to parse the problem -- list index out of range

### ISSUE THREAD

**Issue by memento197** [jan-dolejsi/vscode-pddl#140]
Hello :)

As you can see the planner failed to parse the problem/find a plan and I can't tell why?

**/app/plan: line 3: 32513 Segmentation fault      timeout 10 "$(dirname "$0")"/siw-then-bfsf --domain $1 --problem $2 --output $3

/app/plan: line 3: 32513 Segmentation fault      timeout 10 "$(dirname "$0")"/siw-then-bfsf --domain $1 --problem $2 --output $3
Failed to parse the problem -- list index out of range

/app/plan: line 3: 32513 Segmentation fault      timeout 10 "$(dirname "$0")"/siw-then-bfsf --domain $1 --problem $2 --output $3
Planner found 0 plan(s) in 0.473secs.**

Here's a brief description of what I'm trying to do: I have some parts in a location (magazine) and want them to be grasped and dropped in another location (box) by a robot arm. I'd be very thankful if someone could help me out :) 

Please find the domain&problem files below:

`;This is a modelling of a simple case process with only one arm and two main actions: 
;singleGrasp and singleDrop

(define (domain single_arm_process)

;remove requirements that are not needed
(:requirements :strips :typing :conditional-effects :negative-preconditions :equality)

(:types 
location part - object
;enumerate types and their hierarchy here, e.g. shaft gear - part
)
(:constants
arm - object
;magazine box - location (eventually as constants?)
)

(:predicates ;todo: define predicates here
;(Contains ?x - object ?c - container)
   (At ?p - part ?y - location)
   (reachable ?y - location)
   (empty-arm)
   (grasped ?p - part)
   (dropped ?p - part)
)

;define actions here
(:action singleGrasp
    :parameters (?p - part ?x ?y - location) 
    :precondition  (and 
            (At ?p ?x)
            (reachable ?x)
            (empty-arm)
            (not(grasped ?p))
        )
  
    :effect (and 
            (At arm ?y)
            (not (At arm ?x))
            (forall (?p - part)
                (when (and (grasped ?p))
                      (and (At ?p ?y) (not (At ?p ?x)))
                )
            )
        )
)

(:action singleDrop
    :parameters (?p - part ?x ?y - location) 
    :precondition  (and 
            (At ?p ?x)
            (reachable ?x)
            (not(empty-arm))
            (grasped ?p)
        )
  
    :effect (and 
            (At arm ?y)
            (not (At arm ?x))
            (forall (?p - part)
                (when (and (dropped ?p))
                      (and (At ?p ?y) (not (At ?p ?x)))
                )
            )
        )
)

)`
`(define (problem single_arm_process_solve) 
(:domain single_arm_process)
(:objects
part location - object
box magazine - location 
)

(:init
    ;todo: put the initial state's facts and numeric values here
        (At magazine part)
        (not(At box part))
        (empty-arm)
        (not (grasped part))
        (not (dropped part))
        
)

(:goal 
        (and
        (not(At magazine part))
        (At box part)
        )
      

    ;todo: put the goal condition here
)

)
`

**Comment by haz** [comment]
I'd suggest the following...

1. Try to get this working on the [online editor](http://editor.planning.domains/) (or on a locally installed planner), so you can debug things without assuming an issue with the plugin.
2. Double check your brackets are matching up as you would expect them to.
3. Make sure your domain/problem are in separate files.
4. Simplify your domain/problem until you can get a single action working, then progressively make it more complex again.

Beyond that, you'll probably want to reach out on the [slack channel](http://slack.planning.domains/) for further help, as almost certainly this is an issue with the model and not the vscode plugin.
