### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by senpl** [jan-dolejsi/vscode-pddl#20]
I got that notification so i post it. I hope it will be enough to reproduce it.
[jan-dolejsi.pddl-unresponsive.cpuprofile.txt](https://github.com/jan-dolejsi/vscode-pddl/files/2840659/jan-dolejsi.pddl-unresponsive.cpuprofile.txt)
[jan-dolejsi.pddl-unresponsive.cpuprofile.zip](https://github.com/jan-dolejsi/vscode-pddl/files/2840667/jan-dolejsi.pddl-unresponsive.cpuprofile.zip)
[jan-dolejsi.pddl-unresponsive.cpuprofile.zip](https://github.com/jan-dolejsi/vscode-pddl/files/2840672/jan-dolejsi.pddl-unresponsive.cpuprofile.zip)

- Issue Type: `Performance`
- Extension Name: `pddl`
- Extension Version: `2.8.1`
- OS Version: `Linux x64 4.15.0-20-generic`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/m/jan-dolejsi.pddl-unresponsive.cpuprofile.txt` :warning:
[jan-dolejsi.pddl-unresponsive.cpuprofile.txt](https://github.com/jan-dolejsi/vscode-pddl/files/2840653/jan-dolejsi.pddl-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jan-dolejsi** [comment]
Thanks. Investigating!

**Comment by jan-dolejsi** [comment]
@senpl, unfortunately the dumps do not include the name of the extension or anything I would recognize. Did you observe a performance problem?

**Comment by senpl** [comment]
In general yes. Was it because this extension I am not sure. I think my main issue is that extension work even when I do not want it to (no file present, not activated or anything). 
That way it contribute to general cpu load. So I guess not starting until user wants would be good improvement. Anyway I uninstall it and not wish to investigate it any longer.

**Comment by jan-dolejsi** [comment]
Ok, I understand and sorry to hear that.
In any case, this is how the extension gets activated:

  "activationEvents": [
    "onLanguage:pddl",
    "onLanguage:plan",
    "onLanguage:happenings",
    "workspaceContains:**/*.pddl",
    "workspaceContains:**/*ptest.json",
    "onCommand:pddl.configureParser",
    "onCommand:pddl.configurePlanner",
    "onCommand:pddl.showOverview",
    "onView:pddl.planning.domains"
  ],

If you had any .pddl files in the open workspace, it would load. Was that
the case? I could wait till one of those files gets open,  by removing this
one:

"workspaceContains:**/*.pddl"

**Comment by senpl** [comment]
To me it looks like pddl was autogenerated, because their were always added as git new files, anyway anything that will not eat users cpu when not active is good to have.

**Comment by jan-dolejsi** [comment]
Let's close this as the activation on *.pddl files anywhere in the workspace was disabled.
