### ISSUE TITLE
:requirements ERROR?

### ISSUE THREAD

**Issue by topbobo** [jan-dolejsi/vscode-pddl#33]
I used the default define, but it response this ERROR.
![image](https://user-images.githubusercontent.com/36894425/62184225-a9160a80-b38f-11e9-8ee5-a86169637435.png)

**Comment by topbobo** [comment]
And I don`t know why the "default_object" in the type of the problem file. I have not define this.

**Comment by Maumagnaguagno** [comment]
The planner probably use the ``default_object`` type for objects without a defined type.

**Comment by topbobo** [comment]
> The planner probably uses the `default_object` type for objects without a defined type.

But my problem file have not define the objects.
![image](https://user-images.githubusercontent.com/36894425/62210025-bbaf3480-b3cd-11e9-9077-33e5116f14e2.png)

**Comment by Maumagnaguagno** [comment]
This warning about the types in the problem, for a problem without objects, is indeed confusing.
Can you post your domain file here?

**Comment by topbobo** [comment]
> This warning about the types in the problem, for a problem without objects, is indeed confusing.
> Can you post your domain file here?
Yes, my item is here.
https://github.com/topbobo/mypalnnerstudy

**Comment by Maumagnaguagno** [comment]
It appears that durative-actions are not supported, and the error message is not clear about that.

**Comment by topbobo** [comment]
> It appears that durative-actions are not supported, and the error message is not clear about that.

Thanks.
