### ISSUE TITLE
Search debugger not working

### ISSUE THREAD

**Issue by rrapi** [jan-dolejsi/vscode-pddl#49]
Hello,
I need to run the Search Tree Debugger for a exam project at my university that I have to deliver in few days but don't know why, doesn't appear nothing when I execute the planner.
I tried to configure the planner and the search debugger but still doesn't work. Probably I didn't the right configuration as I am not very familiar with this.
Could anyone help me please?

**Comment by jan-dolejsi** [comment]
Hi, the search debugger needs to be supported by the planner you use. The planner would have to send debug messages to VS Code. The interface is described here [Search-tree-debugger-API](https://github.com/jan-dolejsi/vscode-pddl/wiki/Search-tree-debugger-API). Sadly, I know only one planner that supports this. I think many more planners support output to the GraphViz format. If the planner you are using supports that, you could at least get a static search tree picture.
Perhaps if you save a pddl domain and problem(s) into [planning.domains](http://editor.planning.domains/) and post a session hash code here, I could run the search debugger and generate a search tree for you and perhaps send you a screen cast back?

**Comment by rrapi** [comment]
Hi, the planner I am using is the online service planner: http://solver.planning.domains/solve. But I don't know if it supports the search debugger or not as is the first time I am using it. 
I made a session with the code 8EtRpA64X3 with one domain and problem pddl files and if you can generate a search space tree from this it would really help me a lot. If it's possible to produce an animation it will be perfect but if not a screen cast would be fine.
I have another question: is possible to have a pddl domain with more agents and make this agents work in parallel? I searched but I didn't find nothing about this.

**Comment by rrapi** [comment]
Hi,

Sorry for disturbing again. I just wanted to know if there are news
regarding the search tree.

Best regards,
Franci Rrapi

Il ven 14 feb 2020, 23:53 Jan Dolejší <notifications@github.com> ha scritto:

**Comment by jan-dolejsi** [comment]
Hi again. I am just back from vacation. 

Attached is the plan that I am finding. It is different and shorter than the plan found by the online solver. Along with the plan, please find the .dot file containing the search tree, also rendered into a .svg file (exported using my favorite [Graphviz extension](https://marketplace.visualstudio.com/items?itemName=joaompinto.vscode-graphviz)).
Finally, you can find a .gif and .avi file containing screencast of the search tree generation and a subsequent walkthrough. 
Let me know if this is helpful, or if you had some other output in mind. 
Sorry again that there aren't planners so far readily available that would support this, but hopefully we will get there!

Jan
[rovers-8EtRpA64X3.zip](https://github.com/jan-dolejsi/vscode-pddl/files/4246914/rovers-8EtRpA64X3.zip)
![rovers_8EtRpA64X3](https://user-images.githubusercontent.com/24419357/75192223-1803e800-5754-11ea-9a23-5dec87c12468.gif)
[rovers_8EtRpA64X3.zip](https://github.com/jan-dolejsi/vscode-pddl/files/4246946/rovers_8EtRpA64X3.zip)

**Comment by jan-dolejsi** [comment]
To address the confusion why the search debugger is not displaying anything, when a planning service is called, the extension will now show a warning message that the search debugger config switch is being ignored.

**Comment by jan-dolejsi** [comment]
While I am still waiting for another creator of a planning engine to implement the hooks to populate the search debugger, allow me to close this issue now.

**Comment by jdugit** [comment]
Hi,

The search debugger seems a very useful tool todiagnose the planner behavior on the domain model.
I am trying to use it but nothing is display. I am using the online planner http://solver.planning.domains/solve
I see this issue but not sure about the end.
Could you confirm that the search debugger is not compatible with the online planner?
If it doesn't, have you a planner to recommend in order to use the search debugger?
If not, have you an example to display the tree at the end, even if static output (I am using the VS code PDDL extension)

Thanks a lot for your help
