### ISSUE TITLE
Try HelloWorld overrides domain.pddl file

### ISSUE THREAD

**Issue by ccvca** [jan-dolejsi/vscode-pddl#87]
A click on "Hello World" will override any existing domain.pddl (and problem.pddl? , not tested) without asking.
![grafik](https://user-images.githubusercontent.com/3939648/102346980-05d38e80-3fa0-11eb-873f-e09e2c7e8516.png)

**Comment by jan-dolejsi** [comment]
That would indeed be very undesirable. Especially for the case when version control is not enabled.
