### ISSUE TITLE
How to get the executable?

### ISSUE THREAD

**Issue by Radu-Sebastian** [jan-dolejsi/vscode-pddl#88]
The default planner on http://editor.planning.domains/ doesn't support numerical fluents or durative actions and I want to configure and set a new planner but I can't find the executable you showed in your Configuring the PDDL planner post in that gif.  I have downloaded both LPG and POPF2 planners but I can't find any executable

**Comment by jan-dolejsi** [comment]
That is indeed a usual problem. I understand the executables are usually shared within universities. There is also a great effort around http://solver.planning.domains/ to support multitude of hosted planners, including planners with temporal capabilities. Best to find out about it would be on the Slack channel advertised here: https://planning.wiki/
Even better is the other initiative Christian Muise initiated: to have planner binaries available as Singularity images. That way you could run them on your computer (on Linux, Mac, or on the Windows Subsystem for Linux).

**Comment by haz** [comment]
Aye, once the project takes off, we should be able to hot-swap the planner used on the remote side. The relevant projects are...
* https://github.com/AI-Planning/planutils
* https://github.com/AI-Planning/planning-as-a-service

Project has stalled a bit, but hopefully we'll have a cohort of students hopping on board soon to get it across the finish line.

**Comment by H-Louadah** [comment]
@Radu-Sebastian

I have installed a Linux vm and added the POPF2
No excecutable or jar for popf, and to be honest, even POPF is limited, no negative conditions, no numerical conditions.....

**Comment by jan-dolejsi** [comment]
Sounds like we can close this. Let us know otherwise, or use the slack channel.
